[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm run build"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Content-Type = "text/javascript"
