[build]
  publish = "frontend/dist"
  command = "cd frontend && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/js/*"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/css/*"
  [headers.values]
    Content-Type = "text/css"
