[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[start]
cmd = "cd backend && gunicorn portfolio_backend.wsgi:application --bind 0.0.0.0:$PORT"
